### ISSUE TITLE
Enhancement: Display overriden vs. default values of attributes in publisher UI

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-core#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

With attributes, there is no way to know if artist changed value on them from default.

### How would you imagine the implementation of the feature?

This could be easily shown just by changing font-face or color. Something like:

foo: [bar] (default)
*foo:* [goo] (overriden)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[AY-2614](https://app.clickup.com/t/86bxpfm5u)]

**Comment by BigRoy** [comment]
I personally like the way Houdini displays non-default values with bold value:

![image](https://github.com/ynput/ayon-core/assets/2439881/ad95be14-651a-45de-8a29-8a36e6cb6d00)

Note e.g. here the `Transform` tab being bold because there are children with non-default values.
Then the Translate Y and first dropdown of Transform Order here are non-default values, shown by bold values.

It's not super in your face that it gets annoying but it's obvious enough when you want to look at what is at a default value or not.

👍 

---

Might be a separate feature request, but bonus points for being able to right click and "Revert to defaults" or something along those lines.
