### ISSUE TITLE
Publisher: Optional "This is not your fault" gif

### ISSUE THREAD

**Issue by tokejepsen** [ynput/ayon-core#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

The `This is not your fault` page in the publisher, is not but fun enough, so we need to enhance it with an optional gif from "Good Will Hunting".

https://tenor.com/en-GB/view/its-not-your-fault-supportive-crying-not-your-fault-gif-3707453

### How would you imagine the implementation of the feature?

Some QT magic to include the GIF on the page. Setting for making it optional.

Obviously will get a copyright take down of the repository, but its worth it.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by BigRoy** [comment]
> Obviously will get a copyright take down of the repository, but its worth it.

After the OpenPype repository being taken down briefly due to someone sharing security details in a PR I'm not sure that's _really_ worth it, hehe.

Anyway - I'd actually prefer the "It's not your fault" page to provide more details on the error instead of hiding it all away. The current design is a bit as if the user has no control whatsoever to fix it - which e.g. in the case of raised `KnownPublishError` might not necessarily be the case? Of course, we should make things crash less - but an extractor failing may just occur if we know _what_ might have caused it. (E.g. artist being able to interrupt an export process in the DCC - which ironically _is_ their fault!)

---

Nonetheless, being able to randomize throughout a bunch of gifs could be fun. Not sure if it's worth it - but fun, sure.

Could be more fun if it's gamification instead. We store the amount of errors occurred on that particular user's account and report "Not this shit again." if it happened recently or "You must have missed me!" if it's been long. Ok, bad idea. 🤦

**Comment by mkolar** [comment]
We've talked about this internally and think that this is not worth pursuing at the moment. Closing the issue
