### ISSUE TITLE
Houdini: support `get_publish_families` method

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-core#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Support `get_publish_families` similar to Maya.

### How would you imagine the implementation of the feature?

It's already implemented as part of this PR https://github.com/ynput/ayon-core/pull/295 
But, not made in a separate PR.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[AY-5225](https://app.clickup.com/t/86bymf6uk)]

**Comment by MustafaJafar** [comment]
For reference, I came across this enhancement when drafting a first iteration of model family in Houdini.
without this enhancement the code logic in my case will be interlaced.

**Comment by moonyuet** [comment]
Just my two cents.
For the long term, it is better to have `self.published_families` since we would implement the custom node(i.e. the universal node) for publishing. If we have published families as method, it would help us to build that node as it allows users to decide which families to publish their instances. Although I am not quite sure about the roadmap of the universal node, I personally think that the `get_published_families  implementation helps to build the structure of the custom node a little bit.

**Comment by BigRoy** [comment]
This has now been merged with #295 - I'll close it but feel free to re-open and transfer to `ayon-houdini` if some is still relevant.
