### ISSUE TITLE
Publish Review&Thumbnail unified XP

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-core#583]
As an Artist, I should have the same UX to request a review or thumbnail representation in all(most) hosts.

**Comment by BigRoy** [comment]
Just cross-linking this issue since it seems related: https://github.com/ynput/ayon-core/issues/584

But also, could you expand on the description and explain what is the UX standard we're expecting? What is currently different between hosts? What's good and bad about each? What is currently not aligned between the different ones? etc.

**Comment by dee-ynput** [comment]
Yes, totally a duplicate of #584 
Thanks for spotting it !

I'll close this and continue the discussion in #584
